### ISSUE TITLE
Fail to type "." to go back

### ISSUE THREAD

**Issue by chuang02** [nnnoel/py-uno#1]
This is what happens:
```
: .
Traceback (most recent call last):
  File "uno.py", line 513, in <module>
    game = Game(name)
  File "uno.py", line 52, in __init__
    self.setup_table()
  File "uno.py", line 61, in setup_table
    self.start_game()
  File "uno.py", line 139, in start_game
    self.check_player()
  File "uno.py", line 173, in check_player
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 173, in check_player
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 177, in check_player
    self.user_command_prompt()
  File "uno.py", line 210, in user_command_prompt
    self.see_hand()
  File "uno.py", line 277, in see_hand
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 173, in check_player
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 173, in check_player
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 173, in check_player
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 177, in check_player
    self.user_command_prompt()
  File "uno.py", line 210, in user_command_prompt
    self.see_hand()
  File "uno.py", line 277, in see_hand
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 173, in check_player
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 173, in check_player
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 173, in check_player
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 177, in check_player
    self.user_command_prompt()
  File "uno.py", line 210, in user_command_prompt
    self.see_hand()
  File "uno.py", line 277, in see_hand
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 173, in check_player
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 173, in check_player
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 173, in check_player
    self.next_turn()
  File "uno.py", line 162, in next_turn
    self.check_player()
  File "uno.py", line 177, in check_player
    self.user_command_prompt()
  File "uno.py", line 210, in user_command_prompt
    self.see_hand()
  File "uno.py", line 260, in see_hand
    choice = int(choice)
ValueError: invalid literal for int() with base 10: '.'
```
It is good project and I like it, keep work on it.

**Comment by nnnoel** [comment]
@coder-bts thanks! haven't touched this project in a while, I'll look into it. PRs are also welcome!

**Comment by chuang02** [comment]
@nnnoel Great, I will try to fork this project

**Comment by nnnoel** [comment]
@coder-bts addressed 👍
